[features]
seeds = false
skip-lint = false
[programs.devnet]
gifportal = "GzYepFckF3B1PqvREVMH679hBgdBedcoK4Cf13WXV6hc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/petarpaar/.config/solana/id.json"

[scripts]
test = "node tests/gifportal.js"
